### ISSUE TITLE
Amazon EC2 Instance Retirement 

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/lipidbook#2]
EC2 has detected degradation of the underlying hardware hosting your Amazon EC2 instance (instance-ID: xxxx) associated with your AWS account (AWS Account ID: xxx) in the us-east-1 region. Due to this degradation your instance could already be unreachable. We will stop your instance after 2020-08-20. 

- [x] stop instance
- [x] start instance (to force migration)

**Comment by orbeckst** [comment]
I force-stopped the instance and started it up again but

- Let's Encrypt certificate expired Jun 26, 2020. How do I replace it?
- https://www.lipidbook.org/ failed with **"500 Internal Server Error".** – no idea why

**Comment by orbeckst** [comment]
ping @jandom

**Comment by jandom** [comment]
This is going to be mighty hard for me @orbeckst because i'm away on holiday with on access to the research laptop :(

I'm back in 2 weeks but I'm guessing that's not much help...

**Comment by jandom** [comment]
Wait, wasn't there a gitlab repository you opened for lipidbook? I could totally use that to fix this thing

**Comment by orbeckst** [comment]
Yes,  this one here is the public issue tracker, just in case the public wants to have information. Note that I redacted sensitive information. I'll open an internal issue.
